# Generated by Django 6.0.5 on 2026-06-10 10:49

import chatterbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterbox', '0002_message_image_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=chatterbox.models.chat_image_path),
            preserve_default=False,
        ),
    ]
