# Generated by Django 5.1 on 2024-08-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
